### ISSUE TITLE
erro during running ipattern

### ISSUE THREAD

**Issue by Taylor95** [HaoKeLab/ensembleCNV#6]
Hi,
I got stuck when running ipttern. I followed the scripts in run_ensembleCNV_template.sh but got the erro when running the command:

> {IPNBASE}/preprocess/ilmn/ilmn_run.py --data-file-list   ${WKDIR}/01_initial_call/run_iPattern/data_aux/${PROJECT_NAME}_data_file.txt --gender-file      ${WKDIR}/01_initial_call/run_iPattern/data_au
x/${PROJECT_NAME}_gender_file.txt --bad-sample-file  ${WKDIR}/01_initial_call/run_iPattern/data_aux/${PROJECT_NAME}_bad_samples.txt --experiment       $PROJECT_NAME --output-directory ${WKDIR}/01_initial_call/run_iPattern/results/ --do-log --do-cleanup --noqsub

The erro is:

> SPLIT ALL DATA FAILED.
============================================
Message from stderr:
Splitting files ........
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
    if ipn.all_probes.has_key (E[ipn.snp_name]):
                                               ^
TabError: inconsistent use of tabs and spaces in indentation
------------->>> COLLECTING sample names.
Traceback (most recent call last):
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_all_data_files.py", line 201, in <module>
    split_all_data_files (options)
  File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_all_data_files.py", line 96, in split_all_data_files
    f = open (sample_file)
IOError: [Errno 2] No such file or directory: 'test_dir/201715370233_R01C01.txt.sample.txt'
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode
xkpnode

My data as following after step 'Prepare data for individual CNV callers' :

> [Header]
[Data]
GSGT Version	2.0.3
Processing Date	12/18/2019 7:26 PM
Content		GSAMD-24v1-0_20011747_A1.bpm
Num SNPs	700078
Total SNPs	700078
Num Samples	8959
Total Samples	11074
File 	1 of 896
Sample ID	SNP Name	Chr	Position	Allele1 - Forward	Allele2 - Forward	X	Y	B Allele Freq	Log R Ratio
201715370233_R01C01	1:100292476	1	100292476	A	A	0.807	0.269	0.0000	0.0727
201715370233_R01C01	1:101064936	1	101064936	A	A	3.759	0.832	0.0136	0.5915
201715370233_R01C01	1:103380393	1	103380393	G	G	0.112	0.708	0.9230	-0.1378
201715370233_R01C01	1:104303716	1	104303716	G	G	0.021	0.836	1.0000	0.0444
201715370233_R01C01	1:104864464	1	104864464	G	G	0.472	1.383	0.9962	0.1592
201715370233_R01C01	1:106737318	1	106737318	A	A	0.484	0.039	0.0000	-0.0584
201715370233_R01C01	1:109439680	1	109439680	A	A	0.530	0.027	0.0000	-0.0187
201715370233_R01C01	1:111119214	1	111119214	G	G	0.101	0.911	0.9739	-0.2268
201715370233_R01C01	1:114483147	1	114483147	A	A	1.579	0.025	0.0000	0.3099

Would you help me solve this?
Thank you

**Comment by Taylor95** [comment]
I also find the splitted ipattern, penncnv and quantisnp signal intensity file of the same sample have different lines. For one sample, iPattern has 700079 after removing [Header] section, Penncnv has 690494 lines and Quantisnp has 690394 lines. Shouldn't they be identical?
Moreover, different samples have different lines in Quantisnp. Shouldn't every sample has the same number of markers?

**Comment by Roger1116L** [comment]
> Hi, I got stuck when running ipttern. I followed the scripts in run_ensembleCNV_template.sh but got the erro when running the command:
> 
> > {IPNBASE}/preprocess/ilmn/ilmn_run.py --data-file-list   ${WKDIR}/01_initial_call/run_iPattern/data_aux/${PROJECT_NAME}_data_file.txt --gender-file      ${WKDIR}/01_initial_call/run_iPattern/data_au
> > x/${PROJECT_NAME}_gender_file.txt --bad-sample-file  ${WKDIR}/01_initial_call/run_iPattern/data_aux/${PROJECT_NAME}_bad_samples.txt --experiment       
> >   P
> >   R
> >   O
> >   J
> >   E
> >   C
> >   
> >     T
> >     N
> >   
> >   A
> >   M
> >   E
> >   −
> >   −
> >   o
> >   u
> >   t
> >   p
> >   u
> >   t
> >   −
> >   d
> >   i
> >   r
> >   e
> >   c
> >   t
> >   o
> >   r
> >   y
> > {WKDIR}/01_initial_call/run_iPattern/results/ --do-log --do-cleanup --noqsub
> 
> The erro is:
> 
> > SPLIT ALL DATA FAILED.
> > ============================================
> > Message from stderr:
> > Splitting files ........
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_sample_probe.py", line 36
> > if ipn.all_probes.has_key (E[ipn.snp_name]):
> > ^
> > TabError: inconsistent use of tabs and spaces in indentation
> > ------------->>> COLLECTING sample names.
> > Traceback (most recent call last):
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_all_data_files.py", line 201, in 
> > split_all_data_files (options)
> > File "/dt3/lyq/CNV/ipattern_CNV/ipn_0.581/preprocess/ilmn/split_all_data_files.py", line 96, in split_all_data_files
> > f = open (sample_file)
> > IOError: [Errno 2] No such file or directory: 'test_dir/201715370233_R01C01.txt.sample.txt'
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> > xkpnode
> 
> My data as following after step 'Prepare data for individual CNV callers' :
> 
> > [Header]
> > [Data]
> > GSGT Version	2.0.3
> > Processing Date	12/18/2019 7:26 PM
> > Content		GSAMD-24v1-0_20011747_A1.bpm
> > Num SNPs	700078
> > Total SNPs	700078
> > Num Samples	8959
> > Total Samples	11074
> > File 	1 of 896
> > Sample ID	SNP Name	Chr	Position	Allele1 - Forward	Allele2 - Forward	X	Y	B Allele Freq	Log R Ratio
> > 201715370233_R01C01	1:100292476	1	100292476	A	A	0.807	0.269	0.0000	0.0727
> > 201715370233_R01C01	1:101064936	1	101064936	A	A	3.759	0.832	0.0136	0.5915
> > 201715370233_R01C01	1:103380393	1	103380393	G	G	0.112	0.708	0.9230	-0.1378
> > 201715370233_R01C01	1:104303716	1	104303716	G	G	0.021	0.836	1.0000	0.0444
> > 201715370233_R01C01	1:104864464	1	104864464	G	G	0.472	1.383	0.9962	0.1592
> > 201715370233_R01C01	1:106737318	1	106737318	A	A	0.484	0.039	0.0000	-0.0584
> > 201715370233_R01C01	1:109439680	1	109439680	A	A	0.530	0.027	0.0000	-0.0187
> > 201715370233_R01C01	1:111119214	1	111119214	G	G	0.101	0.911	0.9739	-0.2268
> > 201715370233_R01C01	1:114483147	1	114483147	A	A	1.579	0.025	0.0000	0.3099
> 
> Would you help me solve this? Thank you

Sir, I've met the same error with you when running iPattern , did you work out for then error"No such file or directory: test_dir/xxxxtxt.sample.txt"? I'll appreciate so much if you can offer some solutions! Thank you
